#!/bin/sh
# chkconfig: 2345 90 10
# description: unicorn deamon
# processname: unicorn_deamon

NAME="[ unicorn_deamon ]"
APP_ROOT_DIR="/var/www/app"
PID="/var/www/app/tmp/pids/unicorn.pid"
CMD="bundle exec unicorn -c unicorn.rb -D"
USER=root

start()
{
  if [ -e $PID ]; then
    echo "$NAME already started"
    exit 1
  fi
  echo "$NAME START!"
  sudo su -l ${USER} -c "cd ${APP_ROOT_DIR} && ${CMD}"
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    exit 1
  fi
  echo "$NAME STOP!"
  kill -INT `cat ${PID}`
  rm $PID
}

force_stop()
{
  if [ ! -e ${PID} ]; then
    echo "${NAME} not started"
    exit 1
  fi
  echo "stop ${NAME}"
  kill -INT `cat ${PID}`
}

reload()
{
  if [ ! -e ${PID} ]; then
    echo "${NAME} not started"
    start
    exit 0
  fi
  echo "reload ${NAME}"
  kill -USR2 `cat ${PID}`
}

restart()
{
  if [ -e ${PID} ]; then
    stop
    sleep 3
  fi
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  force-stop)
    force_stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|force-stop|reload|restart]"
    ;;
esac
