#!/bin/sh
# chkconfig: 2345 95 5
# description: crawler for keyakizaka46 blog entries
# processname: crawler_entries

NAME="[ entries crawler ]"
APP_ROOT_DIR="/var/www/app"
PID="/var/www/app/tmp/pids/crawler_entries.pid"
CMD="ruby crawler_entries.rb"
USER=root

start()
{
  if [ -e $PID ]; then
    echo "$NAME already started"
    exit 1
  fi
  echo "$NAME START!"
  sudo su -l ${USER} -c "cd ${APP_ROOT_DIR} && ${CMD}"
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    exit 1
  fi
  echo "$NAME STOP!"
  kill -INT `cat ${PID}`
  rm $PID
}

restart()
{
  stop
  sleep 2
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|restart]"
    ;;
esac
