#!/bin/sh
# chkconfig: 345 90 20
# description: unicorn deamon
# processname: unicorn_deamon

NAME="[ unicorn_deamon ]"
APP_ROOT_DIR="/var/www/app"
PID="/var/www/app/tmp/pids/unicorn.pid"
CMD="bundle exec unicorn -c unicorn.rb -D"
USER=root

start()
{
  if [ -e $PID ]; then
    echo "$NAME already started"
    exit 1
  fi
  echo "$NAME START!"
  sudo su -l ${USER} -c "cd ${APP_ROOT_DIR} && ${CMD}"
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    exit 1
  fi
  echo "$NAME STOP!"
  kill -INT `cat ${PID}`
  rm $PID
}

restart()
{
  stop
  sleep 2
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|restart]"
    ;;
esac
